name: "C++ build"

on:
  push:
    branches: [ master ]

jobs:
    test-win:
        strategy:
            fail-fast: false
            matrix:
                os-version: [ windows-latest ]
                compiler: [ latest ]
        runs-on: ${{ matrix.os-version }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install compiler
                id: install_cc
                uses: rlalik/setup-cpp-compiler@master
                with:
                    compiler: ${{ matrix.compiler }}

            -   name: Check compiler
                shell: bash
                env:
                    CC: ${{ steps.install_cc.outputs.cc }}
                    CXX: ${{ steps.install_cc.outputs.cxx }}
                run: |
                    $CC --version
                    $CXX --version